name: Deobfuscate Py-Fuscate

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Nama file Python yang di-obfuscate'
        required: true
        default: 'iyan-en.py'
      output_filename:
        description: 'Nama file output hasil deobfuscate'
        required: true
        default: 'source.py'

jobs:
  deobfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone PyFuscate_deobfscator
        run: |
          git clone https://github.com/d33znu75/PyFuscate_deobfscator.git

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run deobfuscator
        run: |
          python PyFuscate_deobfscator/deobfuscate.py "${{ github.event.inputs.filename }}" > "${{ github.event.inputs.output_filename }}" 2>&1

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: deobfuscated-source
          path: ${{ github.event.inputs.output_filename }}
